with-expecter: true
dir: tests/unit/mocks
all: true
outpkg: mocks
packages:
  raiseexception.dev/odin/src/accounting/domain/repositories:
    interfaces:
      CategoryRepository:
      AccountRepository:
  raiseexception.dev/odin/src/accounts/domain/repositories:
    interfaces:
      SessionRepository:
      UserRepository:
