template: testify
dir: tests/unit/mocks
pkgname: mocks
filename: mock_{{.InterfaceName}}.go
structname: Mock{{.InterfaceName}}
packages:
  raiseexception.dev/odin/src/accounts/domain/repositories:
    interfaces:
      SessionRepository:
      UserRepository:
  raiseexception.dev/odin/src/vault/domain/repositories:
    interfaces:
      ChunkRepository:
