// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"raiseexception.dev/odin/src/accounting/domain/account"
	"raiseexception.dev/odin/src/accounting/domain/money"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Add(ctx context.Context, account *accountmodel.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *accountmodel.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockAccountRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - account *accountmodel.Account
func (_e *MockAccountRepository_Expecter) Add(ctx any, account any) *MockAccountRepository_Add_Call {
	return &MockAccountRepository_Add_Call{Call: _e.mock.On("Add", ctx, account)}
}

func (_c *MockAccountRepository_Add_Call) Run(run func(ctx context.Context, account *accountmodel.Account)) *MockAccountRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *accountmodel.Account
		if args[1] != nil {
			arg1 = args[1].(*accountmodel.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Add_Call) Return(err error) *MockAccountRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Add_Call) RunAndReturn(run func(ctx context.Context, account *accountmodel.Account) error) *MockAccountRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByNameAndCurrency provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) ExistsByNameAndCurrency(ctx context.Context, name string, currency moneymodel.Currency) (bool, error) {
	ret := _mock.Called(ctx, name, currency)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByNameAndCurrency")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, moneymodel.Currency) (bool, error)); ok {
		return returnFunc(ctx, name, currency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, moneymodel.Currency) bool); ok {
		r0 = returnFunc(ctx, name, currency)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, moneymodel.Currency) error); ok {
		r1 = returnFunc(ctx, name, currency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_ExistsByNameAndCurrency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByNameAndCurrency'
type MockAccountRepository_ExistsByNameAndCurrency_Call struct {
	*mock.Call
}

// ExistsByNameAndCurrency is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - currency moneymodel.Currency
func (_e *MockAccountRepository_Expecter) ExistsByNameAndCurrency(ctx any, name any, currency any) *MockAccountRepository_ExistsByNameAndCurrency_Call {
	return &MockAccountRepository_ExistsByNameAndCurrency_Call{Call: _e.mock.On("ExistsByNameAndCurrency", ctx, name, currency)}
}

func (_c *MockAccountRepository_ExistsByNameAndCurrency_Call) Run(run func(ctx context.Context, name string, currency moneymodel.Currency)) *MockAccountRepository_ExistsByNameAndCurrency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 moneymodel.Currency
		if args[2] != nil {
			arg2 = args[2].(moneymodel.Currency)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAccountRepository_ExistsByNameAndCurrency_Call) Return(b bool, err error) *MockAccountRepository_ExistsByNameAndCurrency_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAccountRepository_ExistsByNameAndCurrency_Call) RunAndReturn(run func(ctx context.Context, name string, currency moneymodel.Currency) (bool, error)) *MockAccountRepository_ExistsByNameAndCurrency_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAll(ctx context.Context) ([]*accountmodel.Account, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*accountmodel.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*accountmodel.Account, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*accountmodel.Account); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*accountmodel.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockAccountRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountRepository_Expecter) GetAll(ctx any) *MockAccountRepository_GetAll_Call {
	return &MockAccountRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockAccountRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockAccountRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetAll_Call) Return(accounts []*accountmodel.Account, err error) *MockAccountRepository_GetAll_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockAccountRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]*accountmodel.Account, error)) *MockAccountRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetByID(ctx context.Context, id string) (*accountmodel.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *accountmodel.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*accountmodel.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *accountmodel.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountmodel.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAccountRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAccountRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAccountRepository_Expecter) GetByID(ctx any, id any) *MockAccountRepository_GetByID_Call {
	return &MockAccountRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAccountRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockAccountRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) Return(account *accountmodel.Account, err error) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockAccountRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*accountmodel.Account, error)) *MockAccountRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) Save(ctx context.Context, account *accountmodel.Account) error {
	ret := _mock.Called(ctx, account)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *accountmodel.Account) error); ok {
		r0 = returnFunc(ctx, account)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAccountRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAccountRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - account *accountmodel.Account
func (_e *MockAccountRepository_Expecter) Save(ctx any, account any) *MockAccountRepository_Save_Call {
	return &MockAccountRepository_Save_Call{Call: _e.mock.On("Save", ctx, account)}
}

func (_c *MockAccountRepository_Save_Call) Run(run func(ctx context.Context, account *accountmodel.Account)) *MockAccountRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *accountmodel.Account
		if args[1] != nil {
			arg1 = args[1].(*accountmodel.Account)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_Save_Call) Return(err error) *MockAccountRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAccountRepository_Save_Call) RunAndReturn(run func(ctx context.Context, account *accountmodel.Account) error) *MockAccountRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
