// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"raiseexception.dev/odin/src/accounting/domain/incomemodel"
)

// NewMockIncomeRepository creates a new instance of MockIncomeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomeRepository {
	mock := &MockIncomeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncomeRepository is an autogenerated mock type for the IncomeRepository type
type MockIncomeRepository struct {
	mock.Mock
}

type MockIncomeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomeRepository) EXPECT() *MockIncomeRepository_Expecter {
	return &MockIncomeRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockIncomeRepository
func (_mock *MockIncomeRepository) Add(ctx context.Context, income *incomemodel.Income) error {
	ret := _mock.Called(ctx, income)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *incomemodel.Income) error); ok {
		r0 = returnFunc(ctx, income)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomeRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockIncomeRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - income *incomemodel.Income
func (_e *MockIncomeRepository_Expecter) Add(ctx any, income any) *MockIncomeRepository_Add_Call {
	return &MockIncomeRepository_Add_Call{Call: _e.mock.On("Add", ctx, income)}
}

func (_c *MockIncomeRepository_Add_Call) Run(run func(ctx context.Context, income *incomemodel.Income)) *MockIncomeRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *incomemodel.Income
		if args[1] != nil {
			arg1 = args[1].(*incomemodel.Income)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIncomeRepository_Add_Call) Return(err error) *MockIncomeRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomeRepository_Add_Call) RunAndReturn(run func(ctx context.Context, income *incomemodel.Income) error) *MockIncomeRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}
