// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"raiseexception.dev/odin/src/accounts/domain/sessionmodel"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Add(ctx context.Context, session *sessionmodel.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sessionmodel.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockSessionRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - session *sessionmodel.Session
func (_e *MockSessionRepository_Expecter) Add(ctx any, session any) *MockSessionRepository_Add_Call {
	return &MockSessionRepository_Add_Call{Call: _e.mock.On("Add", ctx, session)}
}

func (_c *MockSessionRepository_Add_Call) Run(run func(ctx context.Context, session *sessionmodel.Session)) *MockSessionRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sessionmodel.Session
		if args[1] != nil {
			arg1 = args[1].(*sessionmodel.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Add_Call) Return(err error) *MockSessionRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Add_Call) RunAndReturn(run func(ctx context.Context, session *sessionmodel.Session) error) *MockSessionRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Delete(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) Delete(ctx any, token any) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(err error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Get(ctx context.Context, token string) (*sessionmodel.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *sessionmodel.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sessionmodel.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sessionmodel.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessionmodel.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) Get(ctx any, token any) *MockSessionRepository_Get_Call {
	return &MockSessionRepository_Get_Call{Call: _e.mock.On("Get", ctx, token)}
}

func (_c *MockSessionRepository_Get_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Get_Call) Return(session *sessionmodel.Session, err error) *MockSessionRepository_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, token string) (*sessionmodel.Session, error)) *MockSessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Save(ctx context.Context, session *sessionmodel.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sessionmodel.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSessionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session *sessionmodel.Session
func (_e *MockSessionRepository_Expecter) Save(ctx any, session any) *MockSessionRepository_Save_Call {
	return &MockSessionRepository_Save_Call{Call: _e.mock.On("Save", ctx, session)}
}

func (_c *MockSessionRepository_Save_Call) Run(run func(ctx context.Context, session *sessionmodel.Session)) *MockSessionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sessionmodel.Session
		if args[1] != nil {
			arg1 = args[1].(*sessionmodel.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Save_Call) Return(err error) *MockSessionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, session *sessionmodel.Session) error) *MockSessionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
