// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"raiseexception.dev/odin/src/vault/domain/chunkmodel"
)

// NewMockChunkRepository creates a new instance of MockChunkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChunkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChunkRepository {
	mock := &MockChunkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChunkRepository is an autogenerated mock type for the ChunkRepository type
type MockChunkRepository struct {
	mock.Mock
}

type MockChunkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChunkRepository) EXPECT() *MockChunkRepository_Expecter {
	return &MockChunkRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockChunkRepository
func (_mock *MockChunkRepository) Add(ctx context.Context, chunk *chunkmodel.EncryptedChunk) error {
	ret := _mock.Called(ctx, chunk)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *chunkmodel.EncryptedChunk) error); ok {
		r0 = returnFunc(ctx, chunk)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChunkRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockChunkRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - chunk *chunkmodel.EncryptedChunk
func (_e *MockChunkRepository_Expecter) Add(ctx any, chunk any) *MockChunkRepository_Add_Call {
	return &MockChunkRepository_Add_Call{Call: _e.mock.On("Add", ctx, chunk)}
}

func (_c *MockChunkRepository_Add_Call) Run(run func(ctx context.Context, chunk *chunkmodel.EncryptedChunk)) *MockChunkRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *chunkmodel.EncryptedChunk
		if args[1] != nil {
			arg1 = args[1].(*chunkmodel.EncryptedChunk)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChunkRepository_Add_Call) Return(err error) *MockChunkRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChunkRepository_Add_Call) RunAndReturn(run func(ctx context.Context, chunk *chunkmodel.EncryptedChunk) error) *MockChunkRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockChunkRepository
func (_mock *MockChunkRepository) Exists(ctx context.Context, ownerID string, id string) (bool, error) {
	ret := _mock.Called(ctx, ownerID, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, ownerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, ownerID, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, ownerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChunkRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockChunkRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID string
//   - id string
func (_e *MockChunkRepository_Expecter) Exists(ctx any, ownerID any, id any) *MockChunkRepository_Exists_Call {
	return &MockChunkRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, ownerID, id)}
}

func (_c *MockChunkRepository_Exists_Call) Run(run func(ctx context.Context, ownerID string, id string)) *MockChunkRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChunkRepository_Exists_Call) Return(b bool, err error) *MockChunkRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockChunkRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, ownerID string, id string) (bool, error)) *MockChunkRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}
